/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package approject;

import java.awt.Image;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import java.awt.*;
import java.io.ByteArrayOutputStream;
import java.io.FileInputStream;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class AddMovie extends javax.swing.JFrame {
  String filename=null;
  byte[] mimage=null;
   movie m=new movie();
    admin a=new admin();
  String mname;
  String language;
  String t;
  String hours;
  String descrip;
  String d;
  String s_t;
  String e_t;
  String dat;
    /**
     * Creates new form AddMovie
     */
    public AddMovie() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        lang = new javax.swing.JTextField();
        type = new javax.swing.JTextField();
        hour = new javax.swing.JTextField();
        desc = new javax.swing.JTextField();
        day = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        st = new javax.swing.JTextField();
        et = new javax.swing.JTextField();
        Submit = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        date = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        lbl_img = new javax.swing.JLabel();
        chooseimg = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 55)); // NOI18N
        jLabel2.setText("Add Movie");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(360, 0, 343, 97);

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel1.setText("Movie Name:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(330, 100, 160, 29);

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel3.setText("Movie Language:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(330, 150, 210, 29);

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel4.setText("Movie Type:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(330, 200, 170, 29);

        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel5.setText("Movie Hours:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(330, 250, 180, 29);

        jLabel6.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel6.setText("Movie Description:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(320, 300, 230, 30);

        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        getContentPane().add(name);
        name.setBounds(570, 100, 214, 38);
        getContentPane().add(lang);
        lang.setBounds(570, 150, 214, 37);
        getContentPane().add(type);
        type.setBounds(570, 200, 214, 36);
        getContentPane().add(hour);
        hour.setBounds(570, 250, 214, 38);
        getContentPane().add(desc);
        desc.setBounds(570, 300, 214, 35);
        getContentPane().add(day);
        day.setBounds(570, 350, 214, 38);

        jLabel7.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel7.setText("Day:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(330, 340, 100, 40);

        jLabel8.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel8.setText("Starting Time:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(320, 410, 190, 29);

        jLabel9.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel9.setText("Ending Time:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(320, 470, 170, 29);

        st.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stActionPerformed(evt);
            }
        });
        getContentPane().add(st);
        st.setBounds(570, 400, 210, 40);
        getContentPane().add(et);
        et.setBounds(570, 460, 210, 40);

        Submit.setBackground(new java.awt.Color(0, 0, 153));
        Submit.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Submit.setForeground(new java.awt.Color(255, 255, 255));
        Submit.setText("Submit");
        Submit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SubmitMouseClicked(evt);
            }
        });
        Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitActionPerformed(evt);
            }
        });
        getContentPane().add(Submit);
        Submit.setBounds(460, 630, 130, 40);

        jLabel11.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel11.setText("Date:");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(330, 540, 100, 30);
        getContentPane().add(date);
        date.setBounds(570, 520, 210, 50);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setText("Image:");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(850, 220, 70, 30);
        getContentPane().add(lbl_img);
        lbl_img.setBounds(920, 220, 120, 140);

        chooseimg.setBackground(new java.awt.Color(0, 51, 204));
        chooseimg.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        chooseimg.setForeground(new java.awt.Color(255, 255, 255));
        chooseimg.setText("Choose");
        chooseimg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseimgActionPerformed(evt);
            }
        });
        getContentPane().add(chooseimg);
        chooseimg.setBounds(1010, 450, 120, 40);

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\DELL\\Desktop\\movie.jpg")); // NOI18N
        jLabel10.setText("jLabel10");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(0, 0, 2050, 1030);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void stActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stActionPerformed

    private void SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_SubmitActionPerformed

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void chooseimgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseimgActionPerformed
        // TODO add your handling code here:
        
        JFileChooser chooser=new JFileChooser();
       // JLabel lbl_img = new JLabel();
        chooser.showOpenDialog(null);
        File f=chooser.getSelectedFile();
        filename=f.getAbsolutePath();
        System.out.println(filename);
        ImageIcon image_icon=new ImageIcon(new ImageIcon(filename).getImage().getScaledInstance(lbl_img.getWidth(),lbl_img.getHeight(),Image.SCALE_SMOOTH));
        lbl_img.setIcon(image_icon);
        try
        {
            File image=new File(filename);
            FileInputStream fis=new FileInputStream(image);
            ByteArrayOutputStream bos=new ByteArrayOutputStream();
            byte[] buff=new byte[1024];
            for(int readnum;(readnum=fis.read(buff))!=-1;)
            {
                bos.write(buff,0,readnum);
            }
            mimage=bos.toByteArray();
        }
        catch(Exception c)
        {
            JOptionPane.showMessageDialog(null,c);
        }
    }//GEN-LAST:event_chooseimgActionPerformed

    private void SubmitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubmitMouseClicked
        // TODO add your handling code here:
        mname=name.getText();
        language=lang.getText();
        t=type.getText();
        hours=hour.getText();
        descrip=desc.getText();
        d=day.getText();
        s_t=st.getText();
        e_t=et.getText();
        dat=date.getText();
       
       
        a.add_movie(mname,language,t,hours,descrip,s_t,e_t,d,dat,filename,m);
         //mimage=bos.toByteArray();
    }//GEN-LAST:event_SubmitMouseClicked

    /**
     * @param args the command line arguments
     */
    public  void start() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddMovie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddMovie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddMovie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddMovie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddMovie().setVisible(true);
            }
        });
    }

    
       
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Submit;
    private javax.swing.JButton chooseimg;
    private javax.swing.JTextField date;
    private javax.swing.JTextField day;
    private javax.swing.JTextField desc;
    private javax.swing.JTextField et;
    private javax.swing.JTextField hour;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField lang;
    private javax.swing.JLabel lbl_img;
    private javax.swing.JTextField name;
    private javax.swing.JTextField st;
    private javax.swing.JTextField type;
    // End of variables declaration//GEN-END:variables
}
