/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package approject;

/**
 *
 * @author DELL
 */
public class AdminMenu extends javax.swing.JFrame {

    /**
     * Creates new form AdminMenu
     */
    public AdminMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        AddMovie = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        EditMovie = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 65)); // NOI18N
        jLabel2.setText("Menu");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(520, 0, 163, 149);

        AddMovie.setBackground(new java.awt.Color(0, 0, 153));
        AddMovie.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        AddMovie.setForeground(new java.awt.Color(255, 255, 255));
        AddMovie.setText("Add Movie");
        AddMovie.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddMovieMouseClicked(evt);
            }
        });
        AddMovie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddMovieActionPerformed(evt);
            }
        });
        getContentPane().add(AddMovie);
        AddMovie.setBounds(510, 170, 197, 67);

        Delete.setBackground(new java.awt.Color(0, 0, 153));
        Delete.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        Delete.setForeground(new java.awt.Color(255, 255, 255));
        Delete.setText("Delete Movie");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });
        getContentPane().add(Delete);
        Delete.setBounds(510, 270, 197, 65);

        EditMovie.setBackground(new java.awt.Color(0, 0, 153));
        EditMovie.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        EditMovie.setForeground(new java.awt.Color(255, 255, 255));
        EditMovie.setText("Edit Movie");
        EditMovie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditMovieActionPerformed(evt);
            }
        });
        getContentPane().add(EditMovie);
        EditMovie.setBounds(510, 370, 197, 69);

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\DELL\\Desktop\\movie.jpg")); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 1940, 1070);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EditMovieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditMovieActionPerformed
        // TODO add your handling code here:
        EditMovie ed=new EditMovie();
        ed.start();
        
    }//GEN-LAST:event_EditMovieActionPerformed

    private void AddMovieMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddMovieMouseClicked
        // TODO add your handling code here:
        AddMovie ad=new AddMovie();
        ad.start();
    }//GEN-LAST:event_AddMovieMouseClicked

    private void AddMovieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddMovieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddMovieActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        // TODO add your handling code here:
        
        DeleteMovie d=new DeleteMovie();
        d.start();
    }//GEN-LAST:event_DeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void startmenu( ) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddMovie;
    private javax.swing.JButton Delete;
    private javax.swing.JButton EditMovie;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
