/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package approject;
import static com.sun.org.apache.xalan.internal.lib.ExsltDatetime.date;
import com.toedter.*;
import com.toedter.calendar.JCalendar;
import com.toedter.calendar.JDateChooser;
import com.toedter.calendar.JTextFieldDateEditor;
import java.awt.Color;
import java.awt.Image;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class Calendar extends javax.swing.JFrame {
String name,day,startTime,endTime;
static String gd;
static String temp_movie_name;
static String StartTime;
static String EndTime;

    /**
     * Creates new form Calendar
     */
    public Calendar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        search = new javax.swing.JButton();
        label = new javax.swing.JLabel();
        show_detail = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        list = new javax.swing.JList<>();
        nextButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jDateChooser1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jDateChooser1MouseClicked(evt);
            }
        });
        getContentPane().add(jDateChooser1);
        jDateChooser1.setBounds(126, 68, 255, 40);

        search.setBackground(new java.awt.Color(0, 51, 204));
        search.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        search.setForeground(new java.awt.Color(255, 255, 255));
        search.setText("Search");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        getContentPane().add(search);
        search.setBounds(444, 68, 130, 50);
        getContentPane().add(label);
        label.setBounds(840, 80, 210, 249);

        show_detail.setBackground(new java.awt.Color(0, 51, 204));
        show_detail.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        show_detail.setForeground(new java.awt.Color(255, 255, 255));
        show_detail.setText("Show Details");
        show_detail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                show_detailActionPerformed(evt);
            }
        });
        getContentPane().add(show_detail);
        show_detail.setBounds(848, 365, 179, 69);

        jScrollPane1.setViewportView(list);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(817, 474, 246, 219);

        nextButton.setBackground(new java.awt.Color(0, 51, 204));
        nextButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        nextButton.setForeground(new java.awt.Color(255, 255, 255));
        nextButton.setText("Next");
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });
        getContentPane().add(nextButton);
        nextButton.setBounds(890, 741, 100, 45);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\DELL\\Desktop\\movie.jpg")); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 2100, 1290);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jDateChooser1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jDateChooser1MouseClicked
        // TODO add your handling code here:
      SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");

RangeEvaluator evaluator = new RangeEvaluator() {
          @Override
          public Color getInvalidForegroundColor() {
              throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
          }

          @Override
          public Color getInvalidBackroundColor() {
              throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
          }

          @Override
          public String getInvalidTooltip() {
              throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
          }
      };
        try {
            evaluator.setStartDate(dateFormat.parse("2013-09-14"));
        } catch (ParseException ex) {
            Logger.getLogger(Calendar.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            evaluator.setEndDate(dateFormat.parse("2013-09-23"));
        } catch (ParseException ex) {
            Logger.getLogger(Calendar.class.getName()).log(Level.SEVERE, null, ex);
        }

JCalendar calendar = new JCalendar(Locale.UK);
calendar.getDayChooser().addDateEvaluator(evaluator);
        
    }//GEN-LAST:event_jDateChooser1MouseClicked

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
        DateFormat df=new SimpleDateFormat("yyyy-MM-dd");
        Date d=jDateChooser1.getDate();
        gd=(df.format(jDateChooser1.getDate()));
        if(gd.equals("2019-12-05") || gd.equals("2019-12-06") || gd.equals("2019-12-07") || gd.equals("2019-12-08")  || gd.equals("2019-12-09") || gd.equals("2019-12-10") || gd.equals("2019-12-11") || gd.equals("2019-12-12"))
        {    
        admin a=new admin();
        a.Load_movies();
        String img=a.get_detail(gd);
        //System.out.println(img);
        ImageIcon image=new ImageIcon(img);
        Image im=image.getImage();
        Image myImg= im.getScaledInstance(label.getWidth(),label.getHeight(),Image.SCALE_SMOOTH);
        ImageIcon newImage=new ImageIcon(myImg);
        label.setIcon(new javax.swing.ImageIcon(img));
        }
        else
        {
             JOptionPane.showMessageDialog(rootPane,"No movies on that day ");
        }

    }//GEN-LAST:event_searchActionPerformed

    private void show_detailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_show_detailActionPerformed
        // TODO add your handling code here:

         admin a=new admin();
       a.Load_movies();
       movie m=a.GetMovie(gd);
       name=m.movie_name; 
        DefaultListModel DLM=new DefaultListModel();

         day=m.s.get(0).day;
            startTime=m.s.get(0).show_start_time;
            endTime=m.s.get(0).show_end_time;
            temp_movie_name=name;
          StartTime=startTime;
          EndTime=endTime;
            DLM.addElement("Name:  " +name);
            DLM.addElement("Day:  "+day);
            DLM.addElement("Starting Time:  "+startTime);
            DLM.addElement("Ending Time:  "+endTime);
         list.setModel(DLM);
    }//GEN-LAST:event_show_detailActionPerformed

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
        // TODO add your handling code here:
        MovieBooking obj=new MovieBooking();
        obj.start();
    }//GEN-LAST:event_nextButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void start() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calendar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calendar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calendar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calendar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calendar().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label;
    private javax.swing.JList<String> list;
    private javax.swing.JButton nextButton;
    private javax.swing.JButton search;
    private javax.swing.JButton show_detail;
    // End of variables declaration//GEN-END:variables
}
