







/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package approject;

/**
 *
 * @author DELL
 */
public class DisplayPage extends javax.swing.JFrame {

    /**
     * Creates new form DisplayPage
     */
    public DisplayPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Adminbutton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        Customer = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setBackground(new java.awt.Color(0, 0, 204));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 80)); // NOI18N
        jLabel1.setText("Universal Cinemas");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(314, 33, 800, 92);

        Adminbutton.setBackground(new java.awt.Color(0, 0, 255));
        Adminbutton.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Adminbutton.setForeground(new java.awt.Color(255, 255, 255));
        Adminbutton.setText("Admin");
        Adminbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AdminbuttonMouseClicked(evt);
            }
        });
        Adminbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(Adminbutton);
        Adminbutton.setBounds(540, 320, 133, 51);

        jLabel2.setBackground(new java.awt.Color(0, 51, 153));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel2.setText("Login/Signup as:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(260, 220, 399, 48);

        Customer.setBackground(new java.awt.Color(0, 0, 204));
        Customer.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Customer.setForeground(new java.awt.Color(255, 255, 255));
        Customer.setText("Customer");
        Customer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CustomerMouseClicked(evt);
            }
        });
        Customer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustomerActionPerformed(evt);
            }
        });
        getContentPane().add(Customer);
        Customer.setBounds(540, 410, 133, 53);

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\DELL\\Desktop\\movie.jpg")); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 1940, 1090);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AdminbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminbuttonActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_AdminbuttonActionPerformed

    private void AdminbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdminbuttonMouseClicked
        // TODO add your handling code here:
        AdminLoginForm p1=new AdminLoginForm();
        p1.start();
        
    }//GEN-LAST:event_AdminbuttonMouseClicked

    private void CustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CustomerMouseClicked
        // TODO add your handling code here:
        admin a=new admin();
        a.Load_Customer();
        
    }//GEN-LAST:event_CustomerMouseClicked

    private void CustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustomerActionPerformed
        // TODO add your handling code here:
        Calendar c=new Calendar();
        c.start();
        
    }//GEN-LAST:event_CustomerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DisplayPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DisplayPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DisplayPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DisplayPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DisplayPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Adminbutton;
    private javax.swing.JButton Customer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
