/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package approject;

/**
 *
 * @author Sudais Farooq Ch
 */
public class EditMovie extends javax.swing.JFrame {

    /**
     * Creates new form EditMovie
     */
    public EditMovie() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        editday = new javax.swing.JButton();
        edittiming = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 55)); // NOI18N
        jLabel1.setText("Edit Movie");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(400, 40, 261, 54);

        editday.setBackground(new java.awt.Color(0, 0, 153));
        editday.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        editday.setForeground(new java.awt.Color(255, 255, 255));
        editday.setText("Edit Day");
        editday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editdayActionPerformed(evt);
            }
        });
        getContentPane().add(editday);
        editday.setBounds(450, 160, 170, 58);

        edittiming.setBackground(new java.awt.Color(0, 0, 153));
        edittiming.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        edittiming.setForeground(new java.awt.Color(255, 255, 255));
        edittiming.setText("Edit Show Timing");
        edittiming.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edittimingActionPerformed(evt);
            }
        });
        getContentPane().add(edittiming);
        edittiming.setBounds(420, 250, 227, 58);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\DELL\\Desktop\\movie.jpg")); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 1920, 1270);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void editdayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editdayActionPerformed
        // TODO add your handling code here:
        EditMovieDay e=new EditMovieDay();
        e.start();
    }//GEN-LAST:event_editdayActionPerformed

    private void edittimingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edittimingActionPerformed
        // TODO add your handling code here:
        EditMovieTiming e1=new EditMovieTiming();
        e1.start();
    }//GEN-LAST:event_edittimingActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void start() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditMovie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditMovie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditMovie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditMovie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditMovie().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton editday;
    private javax.swing.JButton edittiming;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
