/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package approject;

/**
 *
 * @author Sudais Farooq Ch
 */
public class pay extends javax.swing.JFrame {
static int total;
    /**
     * Creates new form payFarm
     */
    public pay() {
        initComponents();
        amount.setText("500");
       
        String temp=String.valueOf(MovieBooking.seat_count);
        seat.setText(temp);
        total=500*MovieBooking.seat_count;
        payment p=new payment();
        p.amount=total;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        creditcard = new javax.swing.JButton();
        debitcard = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        seat = new javax.swing.JTextField();
        amount = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel1.setText("Select payment method");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(340, 10, 493, 59);

        creditcard.setBackground(new java.awt.Color(0, 0, 153));
        creditcard.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        creditcard.setForeground(new java.awt.Color(255, 255, 255));
        creditcard.setText("Credit Card");
        creditcard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                creditcardMouseClicked(evt);
            }
        });
        creditcard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creditcardActionPerformed(evt);
            }
        });
        getContentPane().add(creditcard);
        creditcard.setBounds(460, 320, 207, 51);

        debitcard.setBackground(new java.awt.Color(0, 0, 153));
        debitcard.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        debitcard.setForeground(new java.awt.Color(255, 255, 255));
        debitcard.setText("Debit Card");
        debitcard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                debitcardMouseClicked(evt);
            }
        });
        getContentPane().add(debitcard);
        debitcard.setBounds(460, 410, 207, 50);

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel2.setText("Total seats:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(390, 110, 180, 44);

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel3.setText("Amount Per Seat:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(390, 210, 220, 29);

        seat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatActionPerformed(evt);
            }
        });
        getContentPane().add(seat);
        seat.setBounds(630, 110, 97, 44);

        amount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amountActionPerformed(evt);
            }
        });
        getContentPane().add(amount);
        amount.setBounds(630, 200, 97, 43);

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\DELL\\Desktop\\movie.jpg")); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 2070, 1300);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void creditcardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creditcardActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_creditcardActionPerformed

    private void creditcardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_creditcardMouseClicked
        // TODO add your handling code here:
        creditCard1 c=new creditCard1();
        c.start();
    }//GEN-LAST:event_creditcardMouseClicked

    private void debitcardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_debitcardMouseClicked
        // TODO add your handling code here:
        GiftCard1 c=new GiftCard1();
       c.start();
    }//GEN-LAST:event_debitcardMouseClicked

    private void amountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amountActionPerformed
        // TODO add your handling code here:
        
//        String i="500";
//        amount.setText(i);
        
    }//GEN-LAST:event_amountActionPerformed

    private void seatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatActionPerformed
        // TODO add your handling code here:
       
        
    }//GEN-LAST:event_seatActionPerformed

    /**
     * @param args the command line arguments
     */
    public  void start() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pay().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField amount;
    private javax.swing.JButton creditcard;
    private javax.swing.JButton debitcard;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField seat;
    // End of variables declaration//GEN-END:variables
}
