/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package approject;

/**
 *
 * @author DELL
 */
public class signup extends javax.swing.JFrame {
    String u_name;
    String pass;
    String name;
    String phn;
    String address;
    String email;

    /**
     * Creates new form signup
     */
    public signup() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        name1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        phn1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        mail1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        u1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        p1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        a1 = new javax.swing.JTextField();
        singup = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setText("Signup Form");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(313, 36, 323, 59);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Name:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(283, 144, 100, 33);

        name1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name1ActionPerformed(evt);
            }
        });
        getContentPane().add(name1);
        name1.setBounds(442, 144, 194, 33);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("Ph Number:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(283, 206, 155, 30);

        phn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phn1ActionPerformed(evt);
            }
        });
        getContentPane().add(phn1);
        phn1.setBounds(443, 206, 193, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("Email:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(283, 267, 147, 31);

        mail1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mail1ActionPerformed(evt);
            }
        });
        getContentPane().add(mail1);
        mail1.setBounds(442, 267, 194, 31);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("Username:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(283, 332, 147, 30);

        u1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                u1ActionPerformed(evt);
            }
        });
        getContentPane().add(u1);
        u1.setBounds(442, 332, 194, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setText("Password:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(283, 398, 137, 27);

        p1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p1ActionPerformed(evt);
            }
        });
        getContentPane().add(p1);
        p1.setBounds(442, 390, 194, 35);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setText("Address:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(283, 453, 137, 27);

        a1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a1ActionPerformed(evt);
            }
        });
        getContentPane().add(a1);
        a1.setBounds(438, 453, 198, 35);

        singup.setBackground(new java.awt.Color(0, 51, 255));
        singup.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        singup.setForeground(new java.awt.Color(255, 255, 255));
        singup.setText("Sign Up");
        singup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                singupMouseClicked(evt);
            }
        });
        singup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                singupActionPerformed(evt);
            }
        });
        getContentPane().add(singup);
        singup.setBounds(380, 520, 142, 53);

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\DELL\\Desktop\\movie.jpg")); // NOI18N
        jLabel8.setText("jLabel8");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(0, 0, 2070, 1240);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void singupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_singupActionPerformed
        // TODO add your handling code here:
        db d=new db();
        phn=phn1.getText();
        email=mail1.getText();
        address=a1.getText();
         name=name1.getText();
         u_name=u1.getText();
         pass=p1.getText();
        d.insertCustomer(name, phn, email, u_name, pass, address);
        
        
    }//GEN-LAST:event_singupActionPerformed

    private void phn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phn1ActionPerformed
        // TODO add your handling code here:
         phn=phn1.getText();
       // System.out.println(phn);
    }//GEN-LAST:event_phn1ActionPerformed

    private void singupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_singupMouseClicked
        // TODO add your handling code here:
        sign p=new sign();
        p.start();
    }//GEN-LAST:event_singupMouseClicked

    private void mail1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mail1ActionPerformed
        // TODO add your handling code here:
        email=mail1.getText();
        //System.out.println(email);
        
    }//GEN-LAST:event_mail1ActionPerformed

    private void a1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a1ActionPerformed
        // TODO add your handling code here:
         address=a1.getText();
       // System.out.println(address);
    }//GEN-LAST:event_a1ActionPerformed

    private void name1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_name1ActionPerformed
        // TODO add your handling code here:
          name=name1.getText();
       // System.out.println(name);
    }//GEN-LAST:event_name1ActionPerformed

    private void u1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_u1ActionPerformed
        // TODO add your handling code here:
         u_name=u1.getText();
        //System.out.println(u_name);
    }//GEN-LAST:event_u1ActionPerformed

    private void p1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p1ActionPerformed
        // TODO add your handling code here:
        pass=p1.getText();
        //System.out.println(pass);
    }//GEN-LAST:event_p1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public  void start() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new signup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField a1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField mail1;
    private javax.swing.JTextField name1;
    private javax.swing.JTextField p1;
    private javax.swing.JTextField phn1;
    private javax.swing.JButton singup;
    private javax.swing.JTextField u1;
    // End of variables declaration//GEN-END:variables
}
