/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package approject;

/**
 *
 * @author DELL
 */
public class superstar extends javax.swing.JFrame {

    /**
     * Creates new form superstar     */
    public superstar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        jButton33 = new javax.swing.JButton();
        jButton34 = new javax.swing.JButton();
        jButton35 = new javax.swing.JButton();
        jButton36 = new javax.swing.JButton();
        jButton37 = new javax.swing.JButton();
        jButton38 = new javax.swing.JButton();
        jButton39 = new javax.swing.JButton();
        jButton40 = new javax.swing.JButton();
        jButton41 = new javax.swing.JButton();
        jButton42 = new javax.swing.JButton();
        jButton43 = new javax.swing.JButton();
        jButton44 = new javax.swing.JButton();
        jButton45 = new javax.swing.JButton();
        jButton46 = new javax.swing.JButton();
        jButton47 = new javax.swing.JButton();
        jButton48 = new javax.swing.JButton();
        jButton49 = new javax.swing.JButton();
        jButton50 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton51 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(367, 13, 246, 249);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton1.setText("1");
        getContentPane().add(jButton1);
        jButton1.setBounds(255, 361, 49, 37);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton2.setText("2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(316, 361, 48, 37);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton3.setText("3");
        getContentPane().add(jButton3);
        jButton3.setBounds(371, 361, 56, 37);

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton4.setText("4");
        getContentPane().add(jButton4);
        jButton4.setBounds(434, 361, 53, 37);

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton5.setText("5");
        getContentPane().add(jButton5);
        jButton5.setBounds(494, 361, 53, 37);

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton6.setText("6");
        getContentPane().add(jButton6);
        jButton6.setBounds(554, 361, 53, 37);

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton7.setText("7");
        getContentPane().add(jButton7);
        jButton7.setBounds(614, 361, 53, 37);

        jButton8.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton8.setText("8");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8);
        jButton8.setBounds(680, 360, 53, 37);

        jButton9.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton9.setText("9");
        getContentPane().add(jButton9);
        jButton9.setBounds(750, 360, 55, 37);

        jButton10.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton10.setText("10");
        getContentPane().add(jButton10);
        jButton10.setBounds(810, 360, 60, 37);

        jButton11.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton11.setText("11");
        getContentPane().add(jButton11);
        jButton11.setBounds(255, 416, 52, 39);

        jButton12.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton12.setText("12");
        getContentPane().add(jButton12);
        jButton12.setBounds(314, 416, 53, 39);

        jButton13.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton13.setText("13");
        getContentPane().add(jButton13);
        jButton13.setBounds(374, 416, 53, 39);

        jButton14.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton14.setText("14");
        getContentPane().add(jButton14);
        jButton14.setBounds(434, 416, 53, 39);

        jButton15.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton15.setText("15");
        getContentPane().add(jButton15);
        jButton15.setBounds(494, 416, 53, 39);

        jButton16.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton16.setText("16");
        getContentPane().add(jButton16);
        jButton16.setBounds(554, 416, 53, 39);

        jButton17.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton17.setText("17");
        getContentPane().add(jButton17);
        jButton17.setBounds(614, 416, 53, 39);

        jButton18.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton18.setText("18");
        getContentPane().add(jButton18);
        jButton18.setBounds(680, 420, 53, 40);

        jButton19.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton19.setText("19");
        getContentPane().add(jButton19);
        jButton19.setBounds(750, 420, 55, 39);

        jButton20.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton20.setText("20");
        getContentPane().add(jButton20);
        jButton20.setBounds(810, 420, 60, 39);

        jButton21.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton21.setText("21");
        getContentPane().add(jButton21);
        jButton21.setBounds(255, 468, 52, 42);

        jButton22.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton22.setText("31");
        getContentPane().add(jButton22);
        jButton22.setBounds(255, 523, 52, 37);

        jButton23.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton23.setText("41");
        getContentPane().add(jButton23);
        jButton23.setBounds(255, 573, 52, 37);

        jButton24.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton24.setText("22");
        getContentPane().add(jButton24);
        jButton24.setBounds(314, 468, 53, 42);

        jButton25.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton25.setText("23");
        getContentPane().add(jButton25);
        jButton25.setBounds(374, 468, 53, 42);

        jButton26.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton26.setText("24");
        getContentPane().add(jButton26);
        jButton26.setBounds(434, 468, 53, 42);

        jButton27.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton27.setText("32");
        getContentPane().add(jButton27);
        jButton27.setBounds(314, 523, 53, 37);

        jButton28.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton28.setText("42");
        getContentPane().add(jButton28);
        jButton28.setBounds(314, 573, 53, 37);

        jButton29.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton29.setText("43");
        getContentPane().add(jButton29);
        jButton29.setBounds(374, 573, 53, 37);

        jButton30.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton30.setText("33");
        getContentPane().add(jButton30);
        jButton30.setBounds(374, 523, 53, 37);

        jButton31.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton31.setText("34");
        getContentPane().add(jButton31);
        jButton31.setBounds(434, 523, 53, 37);

        jButton32.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton32.setText("44");
        getContentPane().add(jButton32);
        jButton32.setBounds(434, 573, 53, 37);

        jButton33.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton33.setText("25");
        getContentPane().add(jButton33);
        jButton33.setBounds(494, 468, 53, 42);

        jButton34.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton34.setText("27");
        getContentPane().add(jButton34);
        jButton34.setBounds(620, 470, 53, 42);

        jButton35.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton35.setText("35");
        getContentPane().add(jButton35);
        jButton35.setBounds(494, 523, 53, 37);

        jButton36.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton36.setText("36");
        getContentPane().add(jButton36);
        jButton36.setBounds(554, 523, 53, 37);

        jButton37.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton37.setText("37");
        getContentPane().add(jButton37);
        jButton37.setBounds(614, 523, 53, 37);

        jButton38.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton38.setText("49");
        getContentPane().add(jButton38);
        jButton38.setBounds(750, 570, 53, 37);

        jButton39.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton39.setText("39");
        getContentPane().add(jButton39);
        jButton39.setBounds(750, 520, 53, 37);

        jButton40.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton40.setText("26");
        getContentPane().add(jButton40);
        jButton40.setBounds(550, 470, 60, 40);

        jButton41.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton41.setText("28");
        getContentPane().add(jButton41);
        jButton41.setBounds(680, 470, 60, 40);

        jButton42.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton42.setText("29");
        getContentPane().add(jButton42);
        jButton42.setBounds(750, 470, 53, 40);

        jButton43.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton43.setText("45");
        jButton43.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton43ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton43);
        jButton43.setBounds(490, 570, 60, 40);

        jButton44.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton44.setText("46");
        getContentPane().add(jButton44);
        jButton44.setBounds(557, 570, 53, 40);

        jButton45.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton45.setText("47");
        getContentPane().add(jButton45);
        jButton45.setBounds(617, 570, 53, 40);

        jButton46.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton46.setText("38");
        getContentPane().add(jButton46);
        jButton46.setBounds(680, 520, 60, 40);

        jButton47.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton47.setText("30");
        getContentPane().add(jButton47);
        jButton47.setBounds(810, 470, 60, 40);

        jButton48.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton48.setText("40");
        getContentPane().add(jButton48);
        jButton48.setBounds(810, 520, 60, 40);

        jButton49.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton49.setText("48");
        getContentPane().add(jButton49);
        jButton49.setBounds(680, 570, 60, 40);

        jButton50.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton50.setText("50");
        getContentPane().add(jButton50);
        jButton50.setBounds(810, 570, 60, 40);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Movie Show Details:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(160, 20, 190, 50);

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Seats:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(190, 290, 140, 40);

        jButton51.setBackground(new java.awt.Color(0, 51, 204));
        jButton51.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton51.setForeground(new java.awt.Color(255, 255, 255));
        jButton51.setText("Book");
        getContentPane().add(jButton51);
        jButton51.setBounds(510, 670, 120, 60);

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\DELL\\Desktop\\MN7BK7.jpg")); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 1338, 800);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton43ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton43ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton43ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(verna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(verna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(verna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(verna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new verna().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton34;
    private javax.swing.JButton jButton35;
    private javax.swing.JButton jButton36;
    private javax.swing.JButton jButton37;
    private javax.swing.JButton jButton38;
    private javax.swing.JButton jButton39;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton40;
    private javax.swing.JButton jButton41;
    private javax.swing.JButton jButton42;
    private javax.swing.JButton jButton43;
    private javax.swing.JButton jButton44;
    private javax.swing.JButton jButton45;
    private javax.swing.JButton jButton46;
    private javax.swing.JButton jButton47;
    private javax.swing.JButton jButton48;
    private javax.swing.JButton jButton49;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton50;
    private javax.swing.JButton jButton51;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
